### ISSUE TITLE
Build questions ./configure missing?

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#3] opened 2016-11-21 15:18 UTC
Please excuse this is it's novice-level questions.  I am following the INSTALL.md instructions.  I'm on Ubuntu 16.10 x64.  Questions:

1. After cloning the initial Github fizmo project, I did 'git submodule update --init --recursive' - is that correct?
2. I find no ./configure to run.  Is a step missing in the INSTALL.md to run 'autoconf'?
3. after running 'autoconf', I did get a configure. Next I run './configure' but get this error: `configure: error: cannot find install-sh, install.sh, or shtool in . "."/.`  I did apt-get install shtool but the error still persists after rerunning autoconf and ./configure.
4. autoconf reported two problems, listed below.

`configure.ac:51: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:57: error: possibly undefined macro: AM_CONDITIONAL
`

Thank you.

**Comment by BroadcastGames** [comment] 2016-11-21 15:32
ok, some progress, I found instructions on forum: http://www.intfiction.org/forum/viewtopic.php?f=7&t=19868&start=20#p108284

**Comment by BroadcastGames** [comment] 2016-11-21 17:23
I have a second computer running Ubuntu 16.04 LTS x64, and I have the same problem with fizmo-sdl2 and fizmo-ncursesw crashing even with just '--help'.  fizmo-console works fine. Any ideas?

**Comment by BroadcastGames** [comment] 2016-11-21 19:34
Opened Issue #4 related to the Ubuntu 16.04 x64 crashes, I might have found where it is bombing.

Related to ./configure issues. If I do `./configure --enable-tracing` the code fails to compile with make:

     fizmo-ncursesw.c:361: undefined reference to `_trace_log_z_ucs'

**Comment by chrender** [comment] 2016-11-22 23:28
Hi, and thanks for reporting your problem.

First, if you only need fizmo-console or fizmo-ncursesw, you can install these from the package repository using "apt-get install fizmo-console" or "apt-get install fizmo-ncursesw".

For all the other frontends you have to build these from source. Before building, you'll have to install the required development packages by running the following commands as root:

apt-get install gcc make pkg-config autoconf automake
apt-get install libxml2-dev libncursesw5-dev libsdl2-dev
apt-get install libsndfile1-dev libjpeg-dev libpng-dev libfreetype6-dev

For the build itself there are two ways to do this. The first one is by downloading the pre-packed version from the official site:

wget https://fizmo.spellbreaker.org/source/fizmo-0.8.3.tar.gz
tar -xf fizmo-0.8.3.tar.gz
cd fizmo-0.8.3
mkdir -p $HOME/opt/fizmo
./configure --prefix=$HOME/opt/fizmo
make -j4 install
~/opt/fizmo/bin/fizmo-sdl --help


If you need / want the latest beta-ish version from github you can try the following:

git clone --recursive https://github.com/chrender/fizmo
cd fizmo
# The "autoreconf" will generate the configure script and everything else automake needs:
autoreconf -fi
mkdir -p $HOME/opt/fizmo
./configure --prefix=$HOME/opt/fizmo
make -j4 install
~/opt/fizmo/bin/fizmo-sdl --help


I've tried both ways on 16.10 and both appear to work. Maybe you can give it a try to see if this helps.

**Comment by BroadcastGames** [comment] 2016-11-23 00:08
Thank you for the help! I followed your directions for the github checkout.  Good news is that now on one of my 16.10 x64 systems the --help segfault is gone and the **fizmo-ncursesw is now working**.  fizmo-sdl2 is crashing once a story starts after the 'story splash screen' on stories like Bronze.zblorb - again, the same story works fine now with fizmo-ncursesw.

I did ./configure with tracing enabled, here is the trace log: https://gist.githubusercontent.com/BroadcastGames/186fbfa50ca3fd9f690da20cc87019c2/raw/58f7a2ddf3e5c0d57500e0739771de2c63db6eee/tracelog.txt

The only message on crash that appears is `Segmentation fault (core dumped)`, is there a way to compile it or something to get a stacktrace?

**Comment by BroadcastGames** [comment] 2016-11-23 10:38
Some good news. The last reported GIthub build (previous message) was on my Intel laptop system with Intel GPU and Ubuntu 16.10 x64.  I built it this morning on my Intel desktop with Nvidia GPU and Ubuntu 16.04 x64. The fizmo-ncursesw build seems perfect.

**Comment by BroadcastGames** [comment] 2016-11-23 10:58
Good news. I've got a diverse set of hardware, one laptop system with Intel GPU and Ubuntu 16.10 x64 clean install (format partitions, not an upgrade). The other a Nvidia GPU and Ubuntu 16.04 x64.  The previous report was on the Ubuntu 16.10 system and now I've done a fresh github checkout and build on the Ubuntu 16.04 x64 Nvidia GPU system.

I'm getting further! Many games work fine. However, fizmo-sdl2 testing, with tracing enabled has a few problems. I'll open new issues related to specific observations.  Thank you again for the assistance!

**Comment by chrender** [comment] 2016-11-23 13:12
Thanks for the tracelog, this allowed me to reproduce the problem. It appears that you're running fizmo-sdl2 on a screen smaller than the default size – your size appears to be 600×716, default is 800 × 600 – and fizmo doesn't handle the initial resize correctly.

As a workaround, you can set alternate initial screen sizes, so fizmo-sdl2 doesn't have to do the faulty resize, for example:

    fizmo-sdl -ww 640 -wh 480 <story-file>

This made fizmo-sdl2 start up correctly for me, even when running on a smaller screen. Hope this helps for the time being, I'll see that I can fix this in fizmo-sdl2.

**Comment by BroadcastGames** [comment] 2016-11-23 13:26
I was re-reading the trace, and I noticed something: /home/adminsag/.config/fizmo/story-list.txt is being opened for past attempts of stories that you tried?  So, even though I told it to open "Bronze" on the command line, it is also opening up past games?

I say this - because I had fed some Glulx .gblorb stories into fizmo-sdl2 at one point by accident (I had a mix of games in one folder from testing another app)... and I wonder if that was somehow being 'remembered' in story-list.txt and causing some of my unexplained crashes.

If you want, I can open a new issue - the basic behavior of fizmo-sdl2 is if you hand it an incompatible game (Glulx) it just exits without showing any kind of message explaining why. Even if you pass it an invalid filename, it just exits. `~/opt/fizmo/bin/fizmo-sdl2 missingfile`

**Comment by chrender** [comment] 2016-11-24 12:30
Commit 4e7fc51eacf1810da978643cc17d4542e8dfbdf8 fixes the startup problem for linux. Fix for Mac OS X and filter-based SDL-processing still to be done.

**Comment by chrender** [comment] 2016-12-04 15:51
I believe the startup issue is now also solved for filter-based aka Mac OS X-based SDL-processing in d91b0b93fae1d6bdf42e4b664191cbadc6b69ba1.

**Comment by chrender** [comment] 2016-12-04 15:56
The story list keeps track of the story files which have been either opened so far, or found via search actions. Currently these are only used for fizmo-ncursesw – if you're running fizmo-ncursesw all by itself it shows a list of known stories and their descriptions. This data is stored in `~config/fizmo/story-list.txt`. In case there's some entry stored which actually doesn't make sense this shouldn't cause any problems, so for the time being you can simply ignore it.

**Comment by chrender** [comment] 2016-12-04 16:00
It would be nice indeed if you could open two more issues for the missing exit messages and the messed-up terminal state since this issue thread is now getting rather diverse. However, even if you don't open up new issues I'll see that both will get addressed.

**Comment by BroadcastGames** [comment] 2016-12-04 16:16
Thank you for the information and software! Opened two new issues. Have a good week!

**Comment by chrender** [comment] 2016-12-05 06:57
Thank you, and you too. I've now tested the latest version on Ubuntu 16.10, Debian and Mac OS X, and I believe that the startup issue has been fixed for all of them. Since all the other problems now have their own separate issue assigned I'll close this one. Should you still run in any startup-related problems, please let me know.

**Closed by chrender** 2016-12-05 06:57 UTC

**Comment by BroadcastGames** [comment] 2016-12-07 19:29
Regarding closing this issue, has the INSTALL.md actually been updated to reflect these new build instructions?

FYI, I'm having build problems with remglk missing a file. Here is the steps I'm using:

`mkdir fizmo_emptydir
cd fizmo_emptydir
git clone https://github.com/erkyrath/remglk.git
cd remglk
make
cd ..

git clone --recursive https://github.com/chrender/fizmo
cd fizmo
# The “autoreconf” will generate the configure script and everything else automake needs:
autoreconf -fi
mkdir -p $HOME/opt/fizmo
./configure --prefix=$HOME/opt/fizmo --enable-remglk --with-remglk-includedir=../remglk --with-remglk-libdir=../remglk
make -j4 install
`

Results in this error: `glk_interface.c:39:17: fatal error: glk.h: No such file or directory
 #include "glk.h"` (in the middle of the output messages, pretty easy to miss).  I see the file is in remglk/glk.h - am I doing something wrong?

**Comment by BroadcastGames** [comment] 2016-12-07 19:45
ok, digging deeper, I opened a new issue #12 - the problem is that ./configure says the path is fine but the actual compiler doesn't like the '../" relative path.  Using an absolute path works around the issue.

**Comment by chrender** [comment] 2016-12-09 12:26
I've updated the installation instructions in 7880adb8d30fe8522f46d5e1a08210e164a31959 to cover the github sources. As with all the modules, there's now also an “upstream” branch for the fizmo distribution repository which contains everything as required for the distribution tar file (meaning configure, .txts etc).

**Comment by BroadcastGames** [comment] 2016-12-18 15:23
did a fresh checkout today from github, now a new problem:

	checking for /home/user0/linuxTerm/fizmo/fizmo_root7/remglk/glk.h... yes
	checking remglk.h usability... no
	checking remglk.h presence... no
	checking for remglk.h... no
	checking for /home/user0/linuxTerm/fizmo/fizmo_root7/remglk/remglk.h... yes
	checking for main in -lremglk... no
	checking for libremglk in /home/user0/linuxTerm/fizmo/fizmo_root7/remglk... no
	checking for libremglk in /usr/lib... no
	checking for libremglk in /usr/local/lib... no
	Could not find libremglk.
	Try setting the location using --with-remglk-libdir.
	configure: error: Could not find libremglk.

I did a make on remglk and there is a file `libremglk.a` in that folder. Any ideas?
