### ISSUE TITLE
fizmo-sdl2 vs. fizmo-ncursesw, sdl2 opening output with story eliza.z5

### ISSUE THREAD

**Issue by BroadcastGames** [chrender/fizmo#6] opened 2016-11-23 11:32 UTC
Hello. Testing with eliza.z5 from here: http://ifdb.tads.org/viewgame?id=fh8iwavcu4ldm98i  Also noteworthy that the zip file contains the Inform source code for reference.

The opening screen is blank on the sdl2 variation.  the ncursesw shows "Would you like a transcript? (Y/N)". If you press [enter] some output starts to appear.

**Comment by chrender** [comment] 2016-12-15 11:25
Thanks for telling me about this. It turned out that this was caused by a bug in libfizmo's history buffer, it should be fixed in commit 0a11b6396f0aa952197bf819be56b428742d742a of fizmo. I'm still doing some regression tests, in the meantime:

I'd like to put your name in the changelog and the “thank-you” section of the manpage. Is that okay with you, and which name would you like to see there – “BroadcastGames” or something else?

**Comment by BroadcastGames** [comment] 2016-12-18 15:46
you can credit me, "Stephen Gutknecht".

**Comment by chrender** [comment] 2017-03-01 20:58
As of the latest commit fdd5445e2a18f44d6d3bb0bbb300265db8423764 in fizmo, this issue has been fixed.

Thanks for all your work in testing.

**Closed by chrender** 2017-03-01 20:58 UTC
